### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by infiniteAgencyBelgium** [nuxodin/vanilla-cms#1]
When i try to install vanilla i’ve got this error
Fatal error: Uncaught Error: Call to a member function insert() on boolean in /data/sites/web/infiniteagency/subsites/vanilla.infinite.agency/m/error_report/qg.php:110 Stack trace: #0 /data/sites/web/infiniteagency/subsites/vanilla.infinite.agency/m/error_report/qg.php(213): qg\error_report(Array) #1 [internal function]: qg\qg::qg\{closure}() #2 {main} thrown in /data/sites/web/infiniteagency/subsites/vanilla.infinite.agency/m/error_report/qg.php on line 110

**Comment by nuxodin** [comment]
Are there other errors before?

Try to delete the following files:
qg/module_installed.json
qg/qgCacheCounters.txt
qg/qgCacheData.txt
