### ISSUE TITLE
error at install

### ISSUE THREAD

**Issue by ieyring** [nuxodin/vanilla-cms#3]
_get "client::usr_id" not implemented
/m/core/lib/Auth.class.php:28 > > > > > >

**Comment by nuxodin** [comment]
On github, the cms is not up to date.
Please use this index.php to install:

```php
<?php
namespace qg;
//$debug = 1;

//define('QG_HTTPS', true);
define('sysPATH', __DIR__.'/m/');

define('qg_dbname', '#vanilla_db#');
define('qg_dbpass', '#my_secret#');

define('qg_host', 'v7.vanilla-cms.org');

$initFile = sysPATH.'core/sysinit.php';
if ( !( is_file($initFile) && include($initFile) ) ) {
   !is_writable(__DIR__) && die('Failed, '.__DIR__.' is not writable!');
   copy('http://'.qg_host.'/install', 'tmp') ? include('tmp') : die('Failed');
}

qg::need('shwups');
qg::init();
echo cms::render();
```

**Comment by nuxodin** [comment]
Nice that you want to try the CMS!
I can also help you on the phone or remotely.
How'd you find it?

**Comment by ieyring** [comment]
i wanted to test it, but i dont get it installed.

the new installer throws no errors. But i dont get the system to run.

**Comment by nuxodin** [comment]
As we solved the issue using PN, i close it.
